alias pmv='/mnt/sdb/home/pc/codes/papercodes/MGLTools/mgltools_x86_64Linux2_1.5.7/bin/pmv'
alias adt='/mnt/sdb/home/pc/codes/papercodes/MGLTools/mgltools_x86_64Linux2_1.5.7/bin/adt'
alias vision='/mnt/sdb/home/pc/codes/papercodes/MGLTools/mgltools_x86_64Linux2_1.5.7/bin/vision'
alias cadd='/mnt/sdb/home/pc/codes/papercodes/MGLTools/mgltools_x86_64Linux2_1.5.7/bin/cadd'
alias pythonsh='/mnt/sdb/home/pc/codes/papercodes/MGLTools/mgltools_x86_64Linux2_1.5.7/bin/pythonsh'
